version: "3.1"
services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - /home/fcuestas/Documentos/dockerize/initial/src/main/resources:/data
    environment:
      MYSQL_ROOT_PASSWORD: ${pass}
      MYSQL_DATABASE: ${initialdb}
    command: --init-file /data/initial.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=tiger 
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 20

  java:
    image: example/java
    build: ./java
    command: "java -jar ${app}"
    ports:
      - ${portJava}:8080
    volumes:
      - ${javaPath}:/app
    depends_on:
      db:
        condition: service_healthy

  angular:
    image: httpd
    ports:
      - ${portAngular}:80
    volumes:
      - ${angularPath}:/usr/local/apache2/htdocs/

  adminer:
    image: adminer
    restart: always
    ports:
      - ${portAdminer}:8080

  proxy:
    image: example/proxy
    build: ./proxy
    ports:
      - ${port}:80
    depends_on:
      - java

#docker compose --env_file ./env-example up
